name: app
description: "Chat Application"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  faker: ^2.2.0
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1
  fluttertoast: ^8.2.8
  another_flushbar: ^1.12.30

  get_storage: ^2.1.1
  file_picker: ^8.1.3
  image_picker: ^1.1.2
  image_cropper: ^8.0.2

  intl: ^0.19.0
  timeago: ^3.7.0
  get_it: ^8.0.1
  provider: ^6.1.2
  delete_un_used_assets: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  flutter_lints: ^5.0.0

import_sorter:
  emojis: true
  comments: false
  ignored_files:
    - \/test\/*

flutter:
  uses-material-design: true